### ISSUE TITLE
Exception ModuleNotFoundError Error so python3.4 doesn't work fine

### ISSUE THREAD

**Issue by msilva14** [pschmitt/pyrundeck#54]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pyrundeck/rundeck.py", line 12, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pyrundeck/__init__.py", line 2, in <module>
    from .rundeck import Rundeck
  File "/usr/lib/python3.4/site-packages/pyrundeck/rundeck.py", line 13, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

**Comment by msilva14** [comment]
replaced by:
except **ImportError:**
    # Python 3
    from urllib.parse import urljoin


It seems to work fine...

**Comment by pschmitt** [comment]
Urf, python 3.4 has been eol for a while! 

I highly suggest you update asap. But thanks for sharing ;)

Ref: https://www.python.org/downloads/release/python-340/
